"""gogo

Revision ID: 1539201f9f52
Revises: c06314089986
Create Date: 2018-07-02 16:52:06.622436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1539201f9f52'
down_revision = 'c06314089986'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
