"""분리

Revision ID: 555f0470dc2c
Revises: 1539201f9f52
Create Date: 2018-07-02 23:56:02.918782

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '555f0470dc2c'
down_revision = '1539201f9f52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cryptopair',
    sa.Column('base_currency', sa.String(length=50), nullable=False),
    sa.Column('quote_currency', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['base_currency'], ['currency.currency_symbol'], ),
    sa.ForeignKeyConstraint(['quote_currency'], ['currency.currency_symbol'], ),
    sa.PrimaryKeyConstraint('base_currency', 'quote_currency')
    )
    op.drop_constraint('cryptomarket_ibfk_3', 'cryptomarket', type_='foreignkey')
    op.drop_constraint('cryptomarket_ibfk_1', 'cryptomarket', type_='foreignkey')
    op.drop_column('cryptomarket', 'base_currency')
    op.drop_column('cryptomarket', 'quote_currency')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cryptomarket', sa.Column('quote_currency', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('cryptomarket', sa.Column('base_currency', mysql.VARCHAR(length=50), nullable=True))
    op.create_foreign_key('cryptomarket_ibfk_1', 'cryptomarket', 'currency', ['base_currency'], ['currency_symbol'])
    op.create_foreign_key('cryptomarket_ibfk_3', 'cryptomarket', 'currency', ['quote_currency'], ['currency_symbol'])
    op.drop_table('cryptopair')
    # ### end Alembic commands ###