"""분리

Revision ID: 981550529073
Revises: 555f0470dc2c
Create Date: 2018-07-03 04:55:23.881172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '981550529073'
down_revision = '555f0470dc2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cryptomarket', sa.Column('api_src', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cryptomarket', 'api_src')
    # ### end Alembic commands ###
